### PR TITLE
If MCC and MNC are not available, return `null`

### LINKED ISSUE #550: java.lang.RuntimeException: RangeError: repeat count must be non-negative
This happens when you run j2me.js on a phone with no SIM.
The error is in the *pad* function in *util.js*, because the values that we're trying to pad (mobileInfo.network.mcc and mobileInfo.network.mnc) are undefined

### PR DESCRIPTION
**Pull request by TimAbraldes**
Fixes #550

### CODE REVIEW

**Comment by marco-c** [comment]
Actually, I think it'd be better to fix the library libs/mobileInfo.js to allow people with no sim card to use the mnc and mcc as url parameters (like on desktop).

**Comment by TimAbraldes** [comment]
> Actually, I think it'd be better to fix the library libs/mobileInfo.js to allow people with no sim card to use the mnc and mcc as url parameters (like on desktop).

I'd be open to allowing mnc and mcc to be specified somehow, but I thought that we stopped using URL parameters in #851. Also, it seems unlikely that users will know what values to use for mnc and mcc; maybe there's some more friendly way we can expose this ability?

**Comment by marco-c** [comment]
Sorry, I meant it would be good for testing :smile: (where you can still use url parameters)

**Comment by TimAbraldes** [comment]
Ah that makes a lot more sense :smile:. Filed #944

**Pull request merged**
